### ISSUE TITLE
Replace a hard-coded local reference with a NuGet package

### ISSUE THREAD

**Issue by SeanFeldman** [jmarbutt/HangFire.TopicExtensions#1]
https://github.com/jmarbutt/HangFire.TopicExtensions/blob/3847864ccdf390a738e3bb7726cd92a08af663ee/HangFire.TopicExtensions/HangFire.TopicExtensions.csproj#L22

Package feed: https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/

**Comment by jmarbutt** [comment]
Thanks @SeanFeldman I have fixed this
